// <auto-generated />
using System;
using CineReview.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineReview.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251123211244_CineReview")]
    partial class CineReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineReview.Models.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AvaliadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FilmeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NotaArte")
                        .HasColumnType("int");

                    b.Property<int>("NotaAtuacao")
                        .HasColumnType("int");

                    b.Property<int>("NotaCenarios")
                        .HasColumnType("int");

                    b.Property<int>("NotaCinematografia")
                        .HasColumnType("int");

                    b.Property<int>("NotaConstrucaoMundo")
                        .HasColumnType("int");

                    b.Property<int>("NotaDevPersonagens")
                        .HasColumnType("int");

                    b.Property<int>("NotaDirecao")
                        .HasColumnType("int");

                    b.Property<int>("NotaEdicao")
                        .HasColumnType("int");

                    b.Property<int>("NotaEfeitosSonoros")
                        .HasColumnType("int");

                    b.Property<int>("NotaEfeitosVisuais")
                        .HasColumnType("int");

                    b.Property<int>("NotaFigurinos")
                        .HasColumnType("int");

                    b.Property<int>("NotaQualidadeImagem")
                        .HasColumnType("int");

                    b.Property<int>("NotaRitmo")
                        .HasColumnType("int");

                    b.Property<int>("NotaScore")
                        .HasColumnType("int");

                    b.Property<int>("NotaTematica")
                        .HasColumnType("int");

                    b.Property<int>("NotaTrama")
                        .HasColumnType("int");

                    b.Property<Guid?>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FilmeId");

                    b.HasIndex("TemporadaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("CineReview.Models.Episodio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time");

                    b.Property<int>("NumeroEpisodio")
                        .HasColumnType("int");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TemporadaId");

                    b.ToTable("Episodios");
                });

            modelBuilder.Entity("CineReview.Models.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Funcoes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MidiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TemporadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoMembro")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("MidiaId");

                    b.HasIndex("TemporadaId");

                    b.ToTable("Equipes");

                    b.HasDiscriminator<string>("TipoMembro").HasValue("Equipe");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CineReview.Models.Midia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassificacaoIndicativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMidia")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Midias");

                    b.HasDiscriminator<string>("TipoMidia").HasValue("Midia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CineReview.Models.Temporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassificacaoIndicativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("date");

                    b.Property<int>("NumeroTemporada")
                        .HasColumnType("int");

                    b.Property<Guid?>("SerieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SerieId");

                    b.ToTable("Temporadas");
                });

            modelBuilder.Entity("CineReview.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Comum");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MidiaUsuario", b =>
                {
                    b.Property<Guid>("FavoritosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FavoritosId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MidiaUsuario");
                });

            modelBuilder.Entity("CineReview.Models.Ator", b =>
                {
                    b.HasBaseType("CineReview.Models.Equipe");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Ator");
                });

            modelBuilder.Entity("CineReview.Models.EquipeTecnica", b =>
                {
                    b.HasBaseType("CineReview.Models.Equipe");

                    b.HasDiscriminator().HasValue("Tecnico");
                });

            modelBuilder.Entity("CineReview.Models.Filme", b =>
                {
                    b.HasBaseType("CineReview.Models.Midia");

                    b.HasDiscriminator().HasValue("Filme");
                });

            modelBuilder.Entity("CineReview.Models.Serie", b =>
                {
                    b.HasBaseType("CineReview.Models.Midia");

                    b.HasDiscriminator().HasValue("Serie");
                });

            modelBuilder.Entity("CineReview.Models.Administrador", b =>
                {
                    b.HasBaseType("CineReview.Models.Usuario");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("CineReview.Models.Avaliacao", b =>
                {
                    b.HasOne("CineReview.Models.Filme", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("FilmeId");

                    b.HasOne("CineReview.Models.Temporada", null)
                        .WithMany("Avaliacoes")
                        .HasForeignKey("TemporadaId");

                    b.HasOne("CineReview.Models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineReview.Models.Episodio", b =>
                {
                    b.HasOne("CineReview.Models.Temporada", null)
                        .WithMany("Episodios")
                        .HasForeignKey("TemporadaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CineReview.Models.Equipe", b =>
                {
                    b.HasOne("CineReview.Models.Midia", null)
                        .WithMany("Equipe")
                        .HasForeignKey("MidiaId");

                    b.HasOne("CineReview.Models.Temporada", null)
                        .WithMany("Equipe")
                        .HasForeignKey("TemporadaId");
                });

            modelBuilder.Entity("CineReview.Models.Temporada", b =>
                {
                    b.HasOne("CineReview.Models.Serie", null)
                        .WithMany("Temporadas")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MidiaUsuario", b =>
                {
                    b.HasOne("CineReview.Models.Midia", null)
                        .WithMany()
                        .HasForeignKey("FavoritosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineReview.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CineReview.Models.Midia", b =>
                {
                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("CineReview.Models.Temporada", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Episodios");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("CineReview.Models.Usuario", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("CineReview.Models.Filme", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("CineReview.Models.Serie", b =>
                {
                    b.Navigation("Temporadas");
                });
#pragma warning restore 612, 618
        }
    }
}
